kind: pipeline
name: default
type: exec

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - echo building...
      - sh make.sh
    when:
      branch:
        - master
      event:
        - push
    environment:
      GOPROXY: https://goproxy.io,direct
      USERNAME:
        from_secret: docker_username

