---
kind: pipeline
name: default
type: exec

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - echo building...
      - sh make.sh
      - echo "$USERNAME" | base64
      - docker login -u "$USERNAME" -p "$PASSWORD"
    when:
      branch:
        - master
      event:
        - push
    environment:
      GOPROXY: https://goproxy.io,direct
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password

---
kind: pipeline
name: default
type: exec

platform:
  os: darwin
  arch: arm64

steps:
  - name: build
    commands:
      - echo building...
      - sh make.sh
      - echo "$USERNAME" | base64
      - docker login -u "$USERNAME" -p "$PASSWORD"
    when:
      branch:
        - master
      event:
        - push
    environment:
      GOPROXY: https://goproxy.io,direct
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
