name: Build

on:  
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Clone certs
        run: |      
          git clone https://damoncoo:${{ secrets.PAT }}@github.com/damoncoo/certs.git --depth 1 --branch master
          ls 
