name: CI

on:  
  workflow_dispatch:
  
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Clone certs
        run: |      
          git clone https://damoncoo:${{ secrets.PAT }}@github.com/damoncoo/certs.git --depth 1 --branch master
          ls 
          pushd certs/ios
          sh install.sh
