name: Build

on:
  repository_dispatch:
    types: [test]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependency
        run: |
          npm install

      - name: Start Job
        run: |
          echo ${{ github.event.client_payload.url }}
          echo ${{ github.event.client_payload.singer }}   
          echo ${{ github.event.client_payload.name }}
          node index.js -e ${{ github.event.client_payload.end_point }} -U ${{ github.event.client_payload.user }} -P ${{ github.event.client_payload.password }}
